package.json
yarn.lock

bump versions of core and sdr
@W-8776235@

feat: update version of core and sdr

---

LICENSE.txt
package.json
yarn.lock

Bumps dev-scripts to fix external NUTs 
@W-0@

chore: bump dev-scripts

---

src/sourceTracking.ts

support childTypes that are addressable (found in SourceMembers)
@W-10261926@

fix: support addressable child types

---

messages/compatibility.json
src/compatibility.ts

change confusing messaging about tracking files
better support toolbelt commands based on ToolbeltCommand that weren't showing the Try this actions automatically
@W-10657483@

fix: message formatting for GA

---

src/shared/remoteSourceTrackingService.ts

review telemetry and look for types/members that cause problems.  
Create manual workarounds
@W-10784173@

fix: more metadata polling exclusions based on telemetry

---

src/compatibility.ts

reverts mapping from `beta` to `legacy`
@W-10803688@

fix: revert beta/legacy mapping

---

src/compatibility.ts

Clearer messaging and legacy accommodation in command names
@W-10803688@

fix: clearer messaging and legacy accommodation

---

src/shared/localShadowRepo.ts
test/unit/localShadowRepo.test.ts

https://github.com/forcedotcom/source-tracking/pull/132

perf: deduplicate files as they are commited to shadow repo

---

src/sourceTracking.ts

generate a componentSet for pulls from STL
this makes sure we resolve any source-backed components
it also happily makes forceignore work better
NUT here: https://github.com/salesforcecli/plugin-source/pull/471
https://github.com/forcedotcom/cli/issues/1485
[@W-11047555@](https://gus.lightning.force.com/a07EE00000vj4ZuYAI)
https://github.com/forcedotcom/cli/issues/1471
[@W-11003710@](https://gus.lightning.force.com/a07EE00000v1JNUYA2)

feat: comp set for pulls

---

package.json
yarn.lock

fix(deps): major bump sdr

---

package.json
yarn.lock

bumps versions of SDR and sfdx-core
@W-11111111@

fix: bump sdr and core

---

package.json
yarn.lock

bump version of SDR to current
@W-12460543@

fix: bump sdr

---

.github/workflows/test.yml
package.json
yarn.lock

Bump SDR to new major version 8.0.1.  Bump `@salesforce/core` to the latest (matches SDR).
@W-00000000@

fix: bump SDR and core libs

---

package.json
test/tsconfig.json
yarn.lock

Bump some deps and added test-strict ts config
@W-12220467@

fix: enable tsconfig strict null checks in tests

---

package.json
src/shared/functions.ts
test/unit/deleteCustomLabels.test.ts
yarn.lock

refactor: return file as object for consumers and tests

---

package.json
src/sourceTracking.ts
yarn.lock

allows a user to pull multiple deleted CLs and delete the file if they're all deleted
@W-13167950@

fix: pull all deleted CLs will delete file

---

package.json
src/shared/guards.ts
src/shared/remoteChangeIgnoring.ts
src/sourceTracking.ts
yarn.lock

returns componentSets that are filtered by forceignore after calculating where SDR might save the remote-only changes.
https://github.com/forcedotcom/cli/issues/2126
@W-13329259@

fix: ignore remote changes using hypothetical paths

---

README.md

docs: add link to issues only repo

---

package.json
yarn.lock

bump SDR to 9.3.2 for latest registry

fix: bump SDR to 9.3.2 for latest registry

---

package.json
src/shared/expectedSourceMembers.ts
yarn.lock

periodically, I check the sourceMemberPolling timeout events in Azure to see what metadata types/components are holding open deploys and never returning.
This is the [query](https://portal.azure.com#@a974a3dd-1d09-49fc-a8ad-a5e375a1e9eb/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F5c0fef69-a7c5-432b-866f-9dfb8b00a8a4%2FresourceGroups%2Fdevtools%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fcli_appinsights/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA4WQPU8DMQyG9%252F4KK9NVAtGFsQNSO54EtFvVIaQuGPJxip2iO%252FHj8V3ogMSJzZafJ3n1lkgpAvG5DEO%252FllwQXGFJYXvBKLz4gs83zAjRBgSK0Bi2HvmcssNb5%252BmOU9GxxfCC%252BTF5T%252FF1TwFTEbNUu8vpHZ0sAPZ9hwxrkMSSlWrqPxuFI2sIPhgZEXNc3ijeErNSKlSuRcslYxhTHUyo16dio5D05jgqDyIYOp5R7HQVruxWx36GdBoGXRG64IQ9 …

fix: reduce sourceMember polling timeouts

---

package.json
src/sourceTracking.ts
yarn.lock

componentSets generated from STL changes will look in the the project to get their sourceApiVersion
@W-14210217@

fix: stl uses project api version

---

package.json
yarn.lock

bumps SDR library to get fixed CustomObjectTranslation behavior
@W-13193003@

fix: bump sdr to 9.8.1

---

package.json
yarn.lock

Depend on a version of SDR that fixes IdentityVerificationProcDev

fix: bump SDR to 10.2.12

---

package.json
yarn.lock

fix: bump sdr to 10.5.3

---

package.json
src/shared/localComponentSetArray.ts
src/shared/localShadowRepo.ts
src/shared/remoteSourceTrackingService.ts
src/shared/types.ts
src/sourceTracking.ts
test/unit/remoteSourceTracking.test.ts
yarn.lock

- interfaces to types (except 1)
- small fix for no-param-reassign
https://github.com/forcedotcom/sfdx-core/actions/runs/8574106147/job/23500290588?pr=1046#step:12:9

fix: interfaces to types, no-param-reassign for windows normalization

---

src/shared/localShadowRepo.ts

refactor: more functions!

---

src/shared/localShadowRepo.ts
src/sourceTracking.ts
test/nuts/local/commitPerf.nut.ts
test/nuts/local/localTrackingFileMovesDecomposedChild.nut.ts
test/nuts/local/localTrackingFileMovesImage.nut.ts
test/nuts/local/localTrackingFileMovesScale.nut.ts
test/nuts/local/localTrackingScale.nut.ts
test/nuts/local/localTrackingScenario.nut.ts
test/nuts/local/nonTopLevelIgnore.nut.ts
test/nuts/local/pkgDirMatching.nut.ts
test/nuts/local/relativePkgDirs.nut.ts
test/unit/localDetectMovedFiles.test.ts
test/unit/localShadowRepo.test.ts

refactor: registry from STL

---

package.json

Did not release on main merge. 

Force release

---

package.json
src/shared/remoteSourceTrackingService.ts
test/unit/remoteSourceTracking.test.ts
yarn.lock

- new place to handle SourceMember corrections, including the one for this bug
- change incoming QuickActionDefinition (not a real type) to QuickAction
- refactor remoteSourceTracking
https://github.com/forcedotcom/cli/issues/2829
@W-15532236@

fix: quick-action-definition

---

package.json
yarn.lock

unpins/bumps iso-git to the latest version
@W-15715533@

chore: unpin iso-git

---

package.json
src/shared/local/localShadowRepo.ts
src/shared/local/moveDetection.ts
src/sourceTracking.ts
yarn.lock

feat: use oclif/core v4

---

package.json
test/nuts/local/localTrackingFileMoveThenEdit.nut.ts
yarn.lock

fix!: sdr core new major versions

---

package.json

fix: rel major 7

---

.github/dependabot.yml
package.json
yarn.lock

Allows dependabot to update iso-git
Part of [@W-15715533@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-15715533)

Allows dependabot updates of isogit

---

src/sourceTracking.ts

fix https://github.com/salesforcecli/plugin-deploy-retrieve/actions/runs/10410849961/job/28833642982?pr=1130#step:13:351

fix: look for xformer on labels parent type

---

LICENSE.txt
package.json
test/unit/localDetectMovedFiles.test.ts
test/unit/localShadowRepo.test.ts
yarn.lock

fix: bump SDR to 12.11.2

---

package.json
yarn.lock

fix: bump SDR version to 12.12.4

---

package.json
yarn.lock

bump sdr to version 12.14.0, which picks up a new preset for esr decomposition
@W-17680614@

fix: bump sdr to pick up esr preset

---

package.json
yarn.lock

bump SDR to latest
@W-17767556@

W-17767556 - fix: bump sdr to 12.14.8

---

package.json
yarn.lock

bump deps before release
@W-18013371@

W-18013371 - fix: bump deps

---

package.json
yarn.lock

fix: bump SDR version to 12.16.8

---

package.json
yarn.lock

bump to latest isogit, sdr, and core

fix: bump libs

---

package.json
src/shared/remote/remoteSourceTrackingService.ts
test/unit/remote/remoteSourceTracking.test.ts
yarn.lock

keep caches from growing unbounded in multitenant environments
purge instances of RemoteSourceTrackingService > 1 hour old
@W-18349042@

@W-18349042 fix: keep caches from growing unbounded in multitenant environments

---

package.json
src/shared/local/localShadowRepo.ts
test/nuts/local/localTrackingFileMoveChildrenWithSameHash.nut.ts
test/nuts/local/localTrackingFileMoveThenEdit.nut.ts
test/nuts/local/localTrackingFileMovesDecomposedChild.nut.ts
test/nuts/local/localTrackingFileMovesImage.nut.ts
test/nuts/local/localTrackingFileMovesScale.nut.ts
test/unit/localDetectMovedFiles.test.ts
yarn.lock

remove the beta env var and have the opt-in as by default. 
add env var for the opt-out to disable track file moves.
@W-18024242@
original discussion related: https://github.com/forcedotcom/cli/discussions/2682
beta opt-in PR: https://github.com/forcedotcom/source-tracking/pull/574

feat: remove beta and add opt-out - W-18024242
