forcedotcom/source-tracking

.circleci/config.yml, package.json, src/shared/metadataKeys.ts, test/nuts/repros/nested-classes2/README.md, test/nuts/repros/nested-classes2/classes/.gitignore, test/nuts/repros/nested-classes2/classes/ignored/Ignored.cls, test/nuts/repros/nested-classes2/classes/ignored/Ignored.cls-meta.xml, test/nuts/repros/nested-classes2/sfdx-project.json, test/unit/metadataKeys.test.ts, yarn.lock
maps EmailTemplateFolder => EmailFolder using the new registry aliasFor
requires https://github.com/forcedotcom/source-deploy-retrieve/pull/556
@W-10385112@
forcedotcom/cli#1345
=> fix: emailTempalteFolder via aliased types

messages/compatibility.json, src/shared/metadataKeys.ts, src/shared/remoteSourceTrackingService.ts, test/unit/metadataKeys.test.ts, test/unit/remoteSourceTracking.test.ts
bigger queries for sourceMembers
creates a secondary timeout for "after the first batch of sourceMembers are created, how long should I wait on the next batch"?
exclue a bunch of sourceMembers from polling--they can't be the last thing we're waiting on
telemetry for sourceMember polling timeouts (how long, what's missing)
handle issues around foo/lwc/foo/foo.css matching paths wrong
NUTs note: e-bikes changed with the release.  The NUTs in plugin-source are fixed here: https://github.com/salesforcecli/plugin-source/pull/421.  When that PR merges, you should see green here.  Until then, you can run them locally by linking source-tracking into plugin-source first.
fixes at least some of @W-10666968@
QA notes:
DEBUG=* is useful to see what's happening with sourceMemberPolling. You can ctrl-f …
=> fix: increase max-fetch default

package.json, src/shared/localShadowRepo.ts, yarn.lock
requires: https://github.com/isomorphic-git/isomorphic-git/pull/1519
uses the newly added gitignore options on isogit
removes all the .gitignore stashing work from shadowRepo
[@W-10843193@](https://gus.lightning.force.com/a07EE00000sr0XMYAY)
=> feat: let  isogit deal with ignore files

src/shared/localShadowRepo.ts, test/nuts/local/relativePkgDirs.nut.ts
fix how STL deals with pkgDirs that have relative paths
https://github.com/forcedotcom/cli/issues/1444
@W-10886128@
QA:
take any project
change the pkgDir from 'foo' to './foo' (same thing, but different)
source:status should see them
source:push should push them
=> fix: support pkgDir with ./foo

messages/compatibility.json, package.json, src/compatibility.ts, src/shared/localShadowRepo.ts, test/nuts/local/relativePkgDirs.nut.ts, yarn.lock
1. more helpful explanation of what users should do when switching from old to new tracking files
2. changes to support GA of new tracking commands
Notes: NUTs are likely to be failing until the plugin-source PR is in.
[@W-10884581@](https://gus.lightning.force.com/a07EE00000tS431YAC)
=> fix: ga tracking commands compatibility

package.json, src/shared/localShadowRepo.ts, yarn.lock
saw a `EMFILE: too many open files` on windows, so back to `graceful` we go
there's a reset perf NUT that exercises a large commit of all of EDA
[@W-10899802@](https://gus.lightning.force.com/a07EE00000tdwd2YAA)
=> feat: gracful-fs for EMFILE: too many open files

src/sourceTracking.ts
uses absolute paths in the ComponentSet for matching local source to prevent SDR from writing to the wrong locations with relative paths.
@W-0@
=> fix: use absolute paths in ComponentSet for matching local source

src/shared/expectedSourceMembers.ts
Ignore DigitalExperienceBundle, DigitalExperience and DigitalExperienceConfig from source tracking polling
It ignores DigitalExperienceBundle, DigitalExperience, and DigitalExperienceConfig from source tracking polling as these md types don't support source tracking
=> feat: ignore DigitalExperienceBundle, DigitalExperience and DigitalExperienceConfig from source tracking polling

src/shared/expectedSourceMembers.ts
something found while working on https://github.com/forcedotcom/source-deploy-retrieve/pull/726 
polling was being skipped for CustomObject* which inadvertently applied to CustomObjectTranslation 
this fix is standalone, no dependencies on the linked SDR PR
[@W-11811429@](https://gus.lightning.force.com/a07EE000017GLrbYAG)
=> fix: poll for CustomObjectTranslation, but still not CustomObjects

src/shared/expectedSourceMembers.ts
Enable DigitalExperienceBundle, DigitalExperience and DigitalExperienceConfig from source tracking polling
Source tracking is supported for DigitalExperienceBundle, DigitalExperience and DigitalExperienceConfig in 242 release.
So reverting this change https://github.com/forcedotcom/source-tracking/pull/206 and enable them for source tracking polling.
=> Enable DigitalExperienceBundle, DigitalExperience and DigitalExperienceConfig from source tracking polling

.github/workflows/onPushToMain.yml, .github/workflows/onRelease.yml, CHANGELOG.md, LICENSE.txt, package.json, src/shared/localShadowRepo.ts, yarn.lock
Lowers maxFileAdd for non-windows oses
[@W-12256168@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12256168)
=> Allow setting maxFileAdd via env var

package.json, src/shared/localShadowRepo.ts, yarn.lock
Makes `ShadowRepo` class catch `InternalError` from isogit to update its message.
isogit's `InternalError` msg ask users to log an issue in its repo:
https://github.com/isomorphic-git/isomorphic-git/blob/d72cf9160cfeb17ae0a566263d184da06562db0d/src/errors/InternalError.js#L9
this caused a lot of users to log issues with `sf` or vscode extensions there:
https://github.com/isomorphic-git/isomorphic-git/issues?q=is%3Aissue+%22Invalid+checksum%22
**NOTE:** this isn't exactly the scenario users are reporting ("invalid checksum"), but will trigger an `InternalError` in isomorphic git.
empty index err:
https://github.com/isomorphic-git/isomorphic-git/blob/d72cf9160cfeb17ae0a566263d184da06562db0d/src/models/GitIndex.js#L72
invalid checksum err: …
=> fix: catch isogit internal error

package.json, src/sourceTracking.ts, yarn.lock
prevent STL from registering multiple listeners.  Helps where VSCode leaves long-running multiple STL instances around and listeners aren't getting cleaned up.
@W-14157566@
https://github.com/forcedotcom/cli/issues/2441
https://github.com/forcedotcom/cli/issues/2458
https://github.com/forcedotcom/cli/issues/2483
https://github.com/forcedotcom/cli/issues/2476
and, I think, https://github.com/forcedotcom/cli/issues/2439
=> fix: avoid duplicate STL listeners when multiple instances exist

package.json, src/shared/remoteSourceTrackingService.ts, test/unit/remoteSourceTracking.test.ts, yarn.lock
use get/set on remoteSourceTrackingService (avoid non-trackable "set" by mutating getContents)
should work with current ConfigFile and the planned changes
prerequisite for @W-14085765@
=> refactor: reduce configFile mutation

package.json, yarn.lock
bumps SDR dependency to at least 9.7.25
=> fix: bump to SDR 9.7.25

package.json, src/index.ts, src/shared/conflicts.ts, src/shared/remoteSourceTrackingService.ts, src/shared/types.ts, test/unit/metadataKeys.test.ts, test/unit/remoteSourceTracking.test.ts, yarn.lock
> requires https://github.com/forcedotcom/source-tracking/pull/510
required by https://github.com/salesforcecli/plugin-deploy-retrieve/pull/819
1. move missing sourceMembers from log to warnings
2. use the core lockfile stuff (similar to how ConfigFile does it) to prevent tracking file conflicts
3. emit an event to help PDR tell people what's happening with tracking
[@W-14535759@](https://gus.lightning.force.com/a07EE00001f0HOvYAM)
it's part of the solution for https://github.com/forcedotcom/cli/issues/2495
After a deployment, the CLI waits for SourceMembers to be created--the time it spends waiting is based on the deploy size.  This can make it look like a large deployment is "stuck" after it completes.
There are lots of files that don't create SourceMembers, or created SourceMembers …
=> feat: warn about missing sourceMembers

src/shared/remoteSourceTrackingService.ts, test/unit/remoteSourceTracking.test.ts
Catches and logs attempts to decode a SourceMember key that is not decodable to prevent `URIError: URI malformed` during source tracking operations.  Adds a unit test for it.
@W-14842075@
=> fix: catch URI Malformed error

package.json, src/index.ts, src/shared/conflicts.ts, src/shared/functions.ts, src/shared/guards.ts, src/shared/localComponentSetArray.ts, src/shared/localShadowRepo.ts, src/shared/metadataKeys.ts, src/shared/populateFilePaths.ts, src/shared/populateTypesAndNames.ts, src/shared/remoteChangeIgnoring.ts, src/shared/remoteSourceTrackingService.ts, src/shared/types.ts, src/sourceTracking.ts, test/nuts/local/commitPerf.nut.ts, test/nuts/local/partialBundleDelete.nut.ts, test/tsconfig.json, test/unit/conflicts.test.ts, test/unit/deleteCustomLabels.test.ts, test/unit/localShadowRepo.test.ts, test/unit/pathIsInFolder.test.ts, test/unit/remoteSourceTracking.test.ts, tsconfig.json, yarn.lock
> requires https://github.com/forcedotcom/source-deploy-retrieve/pull/1217
componentSet and Resolver allow the passing in a registry.
STL will now resolve the registry once when instantiated, from the projectDir, and pass that around to everything that needs it.
part of making @W-14608988@ work with tracking
=> custom registry support

.github/workflows/releaseWithCoreBundle.yml
This PR is to add a workflow to publish source-tracking-bundle in order to be consumed by vs code extensions repo
@W-15288779@
=> chore: add workflow to publish source-tracking-bundle

package.json, src/shared/functions.ts, src/shared/localComponentSetArray.ts, src/shared/localShadowRepo.ts, src/shared/remoteSourceTrackingService.ts, src/sourceTracking.ts, test/nuts/local/commitPerf.nut.ts, test/nuts/local/customLabelsMetadataKeyTranslation.nut.ts, test/nuts/local/localTrackingScenario.nut.ts, test/nuts/local/nonTopLevelIgnore.nut.ts, test/nuts/local/partialBundleDelete.nut.ts, test/nuts/local/pkgDirMatching.nut.ts, test/nuts/local/relativePkgDirs.nut.ts, test/nuts/local/tracking-scale.nut.ts, test/nuts/mpd.nut.ts, test/tsconfig.json, test/unit/conflicts.test.ts, test/unit/deleteCustomLabels.test.ts, test/unit/localShadowRepo.test.ts, test/unit/remoteSourceTracking.test.ts, tsconfig.json, yarn.lock
core7, etc.
node16 module/moduleResolution
one "actual" change because of typing changes in SfError https://github.com/forcedotcom/source-tracking/pull/564/files#diff-4774812bffb4d5f23a015e0d489b38f62335c3c30ca3d2b6c07760300b346d86R282
[@W-13565856@](https://gus.lightning.force.com/a07EE00001TKq3PYAT)
=> feat!: core7

package.json, src/shared/local/functions.ts, src/shared/local/localShadowRepo.ts, src/shared/local/moveDetection.ts, src/shared/local/types.ts, src/shared/localShadowRepo.ts, src/sourceTracking.ts, test/nuts/local/commitPerf.nut.ts, test/nuts/local/localTrackingFileMovesDecomposedChild.nut.ts, test/nuts/local/localTrackingFileMovesImage.nut.ts, test/nuts/local/localTrackingFileMovesScale.nut.ts, test/nuts/local/localTrackingScale.nut.ts, test/nuts/local/localTrackingScenario.nut.ts, test/nuts/local/nonTopLevelIgnore.nut.ts, test/nuts/local/pkgDirMatching.nut.ts, test/nuts/local/relativePkgDirs.nut.ts, test/unit/localDetectMovedFiles.test.ts, test/unit/localShadowRepo.test.ts, yarn.lock
- hash files using isogit to avoid walking files in trees outside of packageDirs.
- moveScale NUT creates a lot of local files
- reorganize code
- move some non-variable stuff (os, os/env dependent max file moves) in ShadowRepo to consts for all instances.
https://github.com/forcedotcom/cli/issues/2880
@W-15840593@
on exact code from `main`
✔ should show 0 files in git status after moving them (10703ms)
on code from main modified with 100_000 local non-project files, 
✔ should show 0 files in git status after moving them (17424ms)
this PR with 100_000 local non-project files, 
✔ should show 0 files in git status after moving them (12291ms)
=> fix: memory usage on giant repos

package.json, src/shared/remoteSourceTrackingService.ts, yarn.lock
bind the logger methods to the pinoLogger instance.
before, it's possible with SF_LOG_LEVEL=trace to cause 
Error (10): Cannot read properties of undefined (reading 'Symbol(pino.msgPrefix)')
when doing remoteSourceTracking operations
reproducible using `project deploy start`.
=> fix: logger binding

package.json, src/shared/metadataKeys.ts, yarn.lock
Ignore `SourceMember` entries for `ExperienceResource` since children of `ExperienceBundle` are not defined in the SDR registry and not supported by the metadata API.  The entire `ExperienceBundle` must be deployed and retrieved instead.
@W-14870967@
=> fix: ignore ExperienceResource SourceMember entries

.vscode/settings.json, package.json, src/shared/populateFilePaths.ts, src/shared/remoteSourceTrackingService.ts, yarn.lock
fixes these
https://github.com/forcedotcom/eslint-config-salesforce-typescript/actions/runs/9703130477/job/26780557045?pr=246
see inline note about bad error message
=> fix: bad error message for missing components,  ts5.5, linter change

package.json, src/shared/metadataKeys.ts, src/shared/populateFilePaths.ts, src/shared/populateTypesAndNames.ts, src/shared/remoteChangeIgnoring.ts, src/shared/types.ts, src/sourceTracking.ts, test/unit/metadataKeys.test.ts, yarn.lock
> this does NOT require the SDR change to be merged first.  It might be easier to merge this PR first (it'll have no effect) to help QA the SDR PR 
- there was some custom logic in STL for labels that isn't necessary with the beta preset.
- use the registry STL already has in more places
- use more top-level imports from `sfdx-core`
[@W-16375268@](https://gus.lightning.force.com/a07EE00001xqSEpYAM)
=> fix: changes for customLabelsBeta v2

.github/workflows/onRelease.yml, .github/workflows/releaseWithCoreBundle.yml
- Adds a check to skip publish job if it's a beta release
@W-16304265@
=> chore: modify workflows to skip publish upon beta release

package.json, src/shared/remoteSourceTrackingService.ts, test/unit/remoteSourceTracking.test.ts, yarn.lock
Adds support for:
`SFDX_DISABLE_SOURCE_MEMBER_POLLING`
`SF_DISABLE_SOURCE_MEMBER_POLLING`
`SFDX_SOURCE_MEMBER_POLLING_TIMEOUT`
`SF_SOURCE_MEMBER_POLLING_TIMEOUT`
Previously, only the SFDX_ prefixed env vars were used.
@W-16648418@
=> fix: support SF_ and SFDX_ prefixed env vars

package.json, src/shared/remoteSourceTrackingService.ts, test/unit/remoteSourceTracking.test.ts, yarn.lock
Some SourceMember types are mapped to different metadata types in SDR.  EmailTemplateFolder is one of them; it maps to EmailFolder which is treated as an alias in SDR.  The FullName parsing was updated to use the entire FullName rather than following a substring pattern for other mapped types like Aura and LWC.
@W-16618249@
https://github.com/forcedotcom/cli/issues/2902
=> fix: resolve fullname correctly for EmailTemplateFolder

.github/workflows/test.yml, src/shared/remote/fileOperations.ts, src/shared/remote/types.ts, src/shared/types.ts, src/sourceTracking.ts, test/unit/remote/fileOperations.test.ts, test/unit/remote/remoteSourceTracking.test.ts
another SourceMember queried/stored field
[@W-17371853@](https://gus.lightning.force.com/a07EE000026MwJ4YAK)
=> feat: last mod date

package.json, src/shared/remote/remoteSourceTrackingService.ts, yarn.lock
reused instances don't keep cache
explanation: RemoteSourceTrackingService(RSTS) is singleton-by-project.
queryCache is used by `querySourceMembersFrom`
For long-running processes (cliaas, vscode, etc) you'd potentially get wrong answers for a project by
1) getChanges (gets changes from last known revision ex: >60)
2) add/edit/delete some metadata
3) instantiate a new SourceTracking on the same project
4) getChanges (hits queryCache for `60` so it doesn't see the new changes)
with this PR, if a new instance of SourceTracking constructs instantiates a RSTS (getting it from the `instanceMap`) it clears the queryCache.
Result:
if you keep using the same instance of SourceTracking, the queryCache in RSTS works like current
if you instantiate a new SourceTracking, the queryCache starts empty …
=> fix: reused instances don't keep cache

package.json, src/shared/functions.ts, src/shared/localComponentSetArray.ts, test/unit/localComponentSetArray.test.ts, test/unit/pathIsInFolder.test.ts, yarn.lock
Clone of https://github.com/forcedotcom/source-tracking/pull/732 with bumped dependencies for tests.
ALL CREDIT GOES TO @lukecotter
What does this PR do?
pathIsInfolder will exit as early as possible,.
This improved overall sf project deploy start times in my project by ~19%
What issues does this PR fix or reference?
Combined with https://github.com/isomorphic-git/isomorphic-git/pull/2023 in isomorphic git I was seeing roughly 45 - 50% faster times working out the changed files to deploy.
there are also some https://github.com/isomorphic-git/isomorphic-git/pull/2063
If it is accepted it would be great to upgrade that too.
Do you want me to create an issue on the [issues repo](https://github.com/forcedotcom/cli/issues)?
=> perf: early exit for pathIsInfolder (19% faster)
